### ISSUE TITLE
Change folder and filename cache

### ISSUE THREAD

**Issue by fahmi182** [budgetneon/pagecache#16]
How to change?, if cache "homepage" the folder name is "home" and filename "home-bla-bla-bal.cache"

Good, if you want to clear only homepage cache :)

**Comment by budgetneon** [comment]
The names of the cached files wouldn't help you much, they are named like yourhost.com_en_USD_1b6cf4016e3f9f567b41634d.cache

They are in various folders under /your/opencart/root/system/cache/pagecache

There is an html comment inside each cache file, at the bottom, though.  

It looks like this:



You could probably write a script to extract the uri, and delete the file if the uri matched what you expected.

**Comment by fahmi182** [comment]
Awesome! thanks.. that works :)
