### ISSUE TITLE
Not working under Firefox?

### ISSUE THREAD

**Issue by adrianmihalko** [budgetneon/pagecache#17]
Hi,

I am just realized, that pagecache is not working from Firefox. 

Under Safari/Chrome is OK.:

![screen shot 2015-04-11 at 22 55 43](https://cloud.githubusercontent.com/assets/733361/7103235/09b8a1d2-e09e-11e4-8240-1b1657f7e494.png)

Can you please check my [site](http://mihalko.eu) from FF (I am using Mac)? I don't see here the comment line generated by pagecache. I am not logged in.

My another question:

It is OK that I see various expire time on same page but from different browser?

![screen shot 2015-04-11 at 23 02 05](https://cloud.githubusercontent.com/assets/733361/7103260/d8120668-e09e-11e4-9879-629ab4fc6ffa.png)

(UP - curl, down Safari)

Thank you very much,
Adrian

**Comment by budgetneon** [comment]
>>I am just realized, that pagecache is not working from Firefox.

Try using Firefox again, but
- Make sure you're logged out of your opencart site
- Make sure there's nothing in your cart

>>It is OK that I see various expire time on same page but from different browser?

That wouldn't be normal no.  Your example above, though, looks like retrievals from two different time periods.   Cached files do expire, at which point they are updated.

There are some other plugins that don't well with the pagecache, like plugins that automatically change language, etc.

**Comment by adrianmihalko** [comment]
Ahhh, I had one product in my cart. So, the problem is solved.

Various expire time:

I just realized that curl is fetching raw domain "http://mydomain.eu", but If I open the site from any browser I am redirected to "http://domain.eu/index.php?route=common/home" - which is same page but it is cached twice. I hope it is not a big problem, but interesting because in both case (curl vs. browser) the uri is same: uri [/]

**Comment by budgetneon** [comment]
Curl will follow redirects if you add the -L switch, but it's not seeing any redirects

>>I don't have any special plugin. 

You appear to be running something called OmFrameWork, which appears to do some things that might not work well with a page cache.

**Comment by adrianmihalko** [comment]
Yeah, I already tried -L switch and even wget, but the result is the same. Even If I disable OmFrameWork (mobile plugin, we already made little change in pagecache to make compatible). I don't have any other idea, but not a big deal. It works.

**Comment by budgetneon** [comment]
I think it is something with OmFramework.   There is another page cache module (it's a paid, not free one), and it looks like they had to specifically do something to work with each other:

https://braiv.zendesk.com/hc/en-us/articles/201356706-Enable-caching-on-the-mobile-site-compatibility-with-OpenCart-PageCache-by-Jay-Gilford-

Unfortunately, since the source code for both omframework and jay's page cache aren't free, I have no way to see what it is that either is doing.
