### ISSUE TITLE
HTML page load error

### ISSUE THREAD

**Issue by mtjhost** [budgetneon/pagecache#21]
Hi This is causing the HTML page load error if keep Cache Enable mode. Whole page structure destroys and layout looks like Text only in lines. 

I use oc2.1.0.2 and Journal Latest version.

**Comment by budgetneon** [comment]
This pagecache is the one that only works on opencart 1.5.x.   You probably, though, are actually using the one meant for opencart 2.x, it's here:  http://github.com/budgetneon/v2pagecache

Also, we can't help with 3rd party themes.   It's just not reasonable for us to purchase/download/install every third party theme and figure out which url's shouldn't be cached for their platform.   You'll need someone that's reasonably well skilled in opencart development to look at the various error logs and see what the issues are.
