### ISSUE TITLE
symbols next to currency icon

### ISSUE THREAD

**Issue by aj1322001** [budgetneon/pagecache#23]
using the standard opencart theme, version 2.1.0.1, 

after install and enable, on front end refresh im getting some strange characters appearing on the left of the currency icon, 

manually adjusted the currency in the conf file but that didnt help, any ideas?

a promising plugin, seems to speed things up!

**Comment by budgetneon** [comment]
You probably don't have a default locale and charset configured for php.

Open the opencart config.php file, and put this in it:

ini_set('intl.default_locale','en_US');
ini_set('default_charset','utf-8');

That's assuming those are right for you.

Then clear the cache and try again.

Mentioned here:

https://github.com/budgetneon/pagecache#locales-and-charsets

Thanks!
