### ISSUE TITLE
Journal 2 theme css breaking

### ISSUE THREAD

**Issue by tomeda** [budgetneon/pagecache#24]
Hi,

I'm using OC 1.5.6.1 with PHP 5.5 and Journal 2 theme.

Before activating page cache my website looks like this http://awesomescreenshot.com/01d5wgmr13
After activating page cache it looks like this http://awesomescreenshot.com/0295wgmu2c

I've enabled `private $cachebydevice='mobiledetect';`

However something is wrong and the cache plugin is not working as it should.

Hope you guide me to some fix. Thanks!

**Comment by budgetneon** [comment]
Sorry, no...I can't help much with 3rd party themes.   They cost money to buy and time to configure, and that's not something we can do...we're not a development shop.

I believe the Journal theme already comes with it's own page cache though.   You might try that instead.
