### ISSUE TITLE
Clean the Expired cache files automatically

### ISSUE THREAD

**Issue by smiraus** [budgetneon/pagecache#25]
Hi, thumbs up for your great extension :+1: 
Is there any possibilty how to setup auto-removal of expired cache files? (i.e. some CRON job command)?

This one:
`find /your_opencart_root/system/cache/pagecache -type f -exec rm {} \;`
purge whole cache but that would be nice to delete only expired files instead of whole cache.
In my case the count of expired cache files grows rapidly and that would be nice to have some tool for automatic clean-up ...

Thanks in advance for any suitable aswer
BR
Michal Smiraus

**Comment by budgetneon** [comment]
See this issue: https://github.com/budgetneon/pagecache/issues/9
