### ISSUE TITLE
installation problem 

### ISSUE THREAD

**Issue by kochler** [budgetneon/pagecache#26]
Hi,

My name is Kochler and i have some problems with pagecache installation.
I try to install your extension Free Page Cache for OC 2.X on my opencart site : www.eatermagazine.ro/Shop and I have this error "Cannot find bottom marker in index.php".
I try to install it manually by your advices but still won't work.

Can you help me?
Thank you
Kochler

**Comment by budgetneon** [comment]
There's a separate github repo for the 2.x version, here: https://github.com/budgetneon/v2pagecache

Two things

a) I haven't looked at whether it works on OpenCart 2.3.x yet, it may well not work there.

b) I just uploaded a new version that should fix some issues on OpenCart 2.2.x.

**Comment by budgetneon** [comment]
Closing because it's opened in the wrong repo.   Re-open in https://github.com/budgetneon/v2pagecache if you like.
